services:
    _defaults:
        autowire: true
        autoconfigure: true

    Akimmaksimov85\CreatorBundle\Command\:
        resource: '../../Command/*'
        tags: [ 'console.command' ]

    Akimmaksimov85\CreatorBundle\Builders\PhpFileBuilder\PhpFileBuilder: ~
    Akimmaksimov85\CreatorBundle\Builders\ContentBuilder\ContentBuilder: ~
    Akimmaksimov85\CreatorBundle\Helpers\StringConverter: ~